# Generated by Django 5.1.3 on 2024-11-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
